from typing import List

from model import Pipeline

import click


def render(pipeline: Pipeline) -> str:
    """
    Генерация .gitlab-ci.yml из нашей модели Pipeline.

    Идея:
      - объявляем stages в порядке pipeline.stages;
      - для каждого Job создаём джобу с тем же именем, stage и image;
      - в script попадают команды из job.script,
        перед ними добавляем echo с названием задачи.
      - В начале файла добавляем человекочитаемую сводку в виде комментариев.
    """

    click.echo("Генерация для GitLab CI/CD...")

    lines: List[str] = []

    # ===== Человекочитаемая шапка =====
    job_names = [job.name for job in pipeline.jobs]
    stages = pipeline.stages or []
    lines.append("# Autogenerated by Self-Deploy (hackathon)")
    lines.append("#")
    lines.append("# ========= Pipeline summary =========")
    if stages:
        lines.append(f"# Stages ({len(stages)}): {', '.join(stages)}")
    else:
        lines.append("# Stages: none")
    if job_names:
        lines.append(f"# Jobs ({len(job_names)}):")
        for name in job_names:
            lines.append(f"#   - {name}")
    else:
        lines.append("# Jobs: none")
    lines.append("# ====================================")
    lines.append("")

    # ===== Оригинальная часть с stages/джобами =====
    lines.append("stages:")
    for stage in pipeline.stages:
        lines.append(f"  - {stage}")
    lines.append("")

    for job in pipeline.jobs:
        click.echo(f"Рендерим задачу {job.name}...")

        # На всякий случай убираем пробелы из имени джобы
        job_name = job.name.replace(" ", "_")

        lines.append(f"{job_name}:")
        lines.append(f"  stage: {job.stage}")

        if getattr(job, "image", None):
            lines.append(f"  image: {job.image}")

        # Команды: заголовок + реальные команды из job.script
        commands: List[str] = []
        commands.append(f"echo 'Job: {job.name}'")
        if job.script:
            commands.extend(job.script)
        else:
            # safety-net: чтобы джоба была валидной даже без скрипта
            commands.append("echo 'TODO: добавьте команды для этой задачи'")

        lines.append("  script:")
        for cmd in commands:
            # немного экранирования, чтобы YAML и шелл не сломались
            safe_cmd = cmd.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    - "{safe_cmd}"')
        lines.append("")

    click.echo("Генерация завершена!")

    return "\n".join(lines)
