from typing import Dict, List

from model import Pipeline, Job
import click


def render(pipeline: Pipeline) -> str:
    """
    Генерация declarative Jenkinsfile из абстрактного Pipeline.

    Особенности:
      - pipeline { agent none } + per-stage agent;
      - стадии идут в порядке pipeline.stages;
      - в каждой стадии последовательно выполняются команды всех задач,
        относящихся к этой стадии;
      - если в стадии указан единственный образ image, используется
        agent { docker { image '...' } }, иначе agent any.
      - В начале файла добавляем человекочитаемую сводку в комментариях.
    """
    click.echo("Генерация для Jenkins...")

    # Группируем задачи по стадии
    stage_jobs: Dict[str, List[Job]] = {}
    for job in pipeline.jobs:
        click.echo(f"Рендерим задачу {job.name}...")
        stage_jobs.setdefault(job.stage, []).append(job)

    lines: List[str] = []

    # ===== Человекочитаемая шапка =====
    job_names = [job.name for job in pipeline.jobs]
    stages = pipeline.stages or []
    lines.append("// Autogenerated by Self-Deploy (hackathon)")
    lines.append("//")
    lines.append("// ========= Pipeline summary =========")
    if stages:
        lines.append(f"// Stages ({len(stages)}): {', '.join(stages)}")
    else:
        lines.append("// Stages: none")
    if job_names:
        lines.append(f"// Jobs ({len(job_names)}):")
        for name in job_names:
            lines.append(f"//   - {name}")
    else:
        lines.append("// Jobs: none")
    lines.append("// ====================================")

    # ===== Оригинальный Jenkinsfile =====
    lines.append("pipeline {")
    # Общий agent отключаем, дальше будут агенты на уровне стадий
    lines.append("    agent none")
    lines.append("    stages {")

    for stage_name in pipeline.stages:
        jobs = stage_jobs.get(stage_name)
        if not jobs:
            # стадия без задач — пропускаем
            continue

        lines.append(f"        stage('{stage_name}') {{")

        # Выбираем agent для стадии
        images = {job.image for job in jobs if job.image}
        if images:
            if len(images) == 1:
                image = next(iter(images))
                lines.append("            agent {")
                lines.append(f"                docker {{ image '{image}' }}")
                lines.append("            }")
            else:
                # несколько разных образов — оставляем agent any и пишем коммент
                lines.append("            agent any")
                img_list = ", ".join(sorted(images))
                lines.append(f"            // NOTE: jobs in this stage use multiple images: {img_list}")
        else:
            lines.append("            agent any")

        lines.append("            steps {")
        for job in jobs:
            # Маркер, какая job сейчас выполняется
            lines.append(f"                echo 'Job: {job.name}'")
            # Команды job.script
            for cmd in (job.script or []):
                safe_cmd = cmd.replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'                sh "{safe_cmd}"')
        lines.append("            }")
        lines.append("        }")

    lines.append("    }")
    lines.append("}")
    lines.append("")

    click.echo("Генерация Jenkinsfile завершена!")

    return "\n".join(lines)
